config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'reports/tipificacion'
  resources :statuses
  resources :areas
  resources :agents
  resources :categories
  root "tickets#index"
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]

  # GET /statuses or /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:name, :closed)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.slim
= simple_form_for(@status) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :closed

  .form-actions
    = f.button :submit

app/views/statuses/edit.html.slim
h1 Editing status

== render 'form'

=> link_to 'Show', @status
'|
=< link_to 'Back', statuses_path

app/views/statuses/index.html.slim
h1 Listing statuses

table
  thead
    tr
      th Name
      th Closed
      th
      th
      th

  tbody
    - @statuses.each do |status|
      tr
        td = status.name
        td = status.closed
        td = link_to 'Show', status
        td = link_to 'Edit', edit_status_path(status)
        td = link_to 'Destroy', status, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Status', new_status_path

app/views/statuses/new.html.slim
h1 New status

== render 'form'

= link_to 'Back', statuses_path

app/views/statuses/show.html.slim
p#notice = notice

p
  strong Name:
  = @status.name
p
  strong Closed:
  = @status.closed

=> link_to 'Edit', edit_status_path(@status)
'|
=< link_to 'Back', statuses_path