config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'reports/tipificacion'
  resources :statuses
  resources :areas
  resources :agents
  resources :categories
  root "tickets#index"
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agent.rb
# == Schema Information
#
# Table name: agents
#
#  id         :bigint           not null, primary key
#  name       :string
#  sid_worker :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  area_id    :bigint
#
# Indexes
#
#  index_agents_on_area_id  (area_id)
#

class Agent < ApplicationRecord
  has_many :tickets
  belongs_to :area

  searchkick

  def search_data
    attributes.merge(custom_data)
  end

  def custom_data
    {
      area_name: area.nil? ? "sin area" : area.name,
    }
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: %i[ show edit update destroy ]

  # GET /agents or /agents.json
  def index
    @agents = Agent.all
  end

  # GET /agents/1 or /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents or /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: "Agent was successfully created." }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1 or /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: "Agent was successfully updated." }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1 or /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: "Agent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agent_params
      params.require(:agent).permit(:name)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/_form.html.slim
= simple_form_for(@agent) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/agents/edit.html.slim
h1 Editing agent

== render 'form'

=> link_to 'Show', @agent
'|
=< link_to 'Back', agents_path

app/views/agents/index.html.slim
h1 Listing agents

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @agents.each do |agent|
      tr
        td = agent.name
        td = link_to 'Show', agent
        td = link_to 'Edit', edit_agent_path(agent)
        td = link_to 'Destroy', agent, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Agent', new_agent_path

app/views/agents/new.html.slim
h1 New agent

== render 'form'

= link_to 'Back', agents_path

app/views/agents/show.html.slim
p#notice = notice

p
  strong Name:
  = @agent.name

=> link_to 'Edit', edit_agent_path(@agent)
'|
=< link_to 'Back', agents_path