config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'reports/tipificacion'
  resources :statuses
  resources :areas
  resources :agents
  resources :categories
  root "tickets#index"
  resources :tickets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/area.rb
# == Schema Information
#
# Table name: areas
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Area < ApplicationRecord
  has_many :tickets, through: :categories
  has_many :statuses
  has_many :categories
  has_many :agents
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: %i[ show edit update destroy ]

  # GET /areas or /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1 or /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas or /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: "Area was successfully created." }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1 or /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: "Area was successfully updated." }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1 or /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: "Area was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def area_params
      params.require(:area).permit(:name)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.slim
= simple_form_for(@area) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit

app/views/areas/edit.html.slim
h1 Editing area

== render 'form'

=> link_to 'Show', @area
'|
=< link_to 'Back', areas_path

app/views/areas/index.html.slim
h1 Listing areas

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @areas.each do |area|
      tr
        td = area.name
        td = link_to 'Show', area
        td = link_to 'Edit', edit_area_path(area)
        td = link_to 'Destroy', area, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Area', new_area_path

app/views/areas/new.html.slim
h1 New area

== render 'form'

= link_to 'Back', areas_path

app/views/areas/show.html.slim
p#notice = notice

p
  strong Name:
  = @area.name

=> link_to 'Edit', edit_area_path(@area)
'|
=< link_to 'Back', areas_path